Global:
  use_gpu: true
  epoch_num: 72
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/custom_rec/best_model/best_accuracy
  save_epoch_step: 3
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints: 
  save_inference_dir: ./
  use_visualdl: False
  infer_img: 
  # for data or label process
  character_dict_path: PaddleOCR/ppocr/utils/en_dict.txt 
  max_text_length: 25 
  num_heads: 8
  infer_mode: True
  use_space_char: False
  save_res_path: ./output/rec/rec_custom.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  clip_norm: 10.0
  lr:
    learning_rate: 0.0001

Architecture:
  model_type: rec
  algorithm: SRN
  in_channels: 1
  Transform:
  Backbone:
    name: ResNetFPN
  Head:
    name: SRNHead
    max_text_length: 25
    num_heads: 8
    num_encoder_TUs: 2
    num_decoder_TUs: 4
    hidden_dims: 512 
    out_channels: 97

Loss:
  name: SRNLoss

PostProcess:
  name: SRNLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    #data_dir: ./label_data/ic15_data/
    data_dir: /data/str/data/cropped_images
    #label_file_list: ["./label_data/ic15_data/rec_gt_train.txt"]
    label_file_list: ["/data/label_data/rec/rec_train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SRNLabelEncode: # Class handling label
      - SRNRecResizeImg:
          image_shape: [1, 64, 256]
      - KeepKeys:
          keep_keys: ['image',
                      'label',
                      'length',
                      'encoder_word_pos',
                      'gsrm_word_pos',
                      'gsrm_slf_attn_bias1',
                      'gsrm_slf_attn_bias2'] # dataloader will return list in this order 
                      
  loader:
    shuffle: False
    batch_size_per_card: 64
    drop_last: False
    num_workers: 4 

Eval:
  dataset:
    name: SimpleDataSet
    #data_dir: ./label_data/ic15_data
    data_dir: /data/str/data/cropped_images
    #label_file_list: ["./label_data/ic15_data/rec_gt_test.txt"] 
    label_file_list: ["/data/label_data/rec/rec_test.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SRNLabelEncode: # Class handling label
      - SRNRecResizeImg:
          image_shape: [1, 64, 256]
      - KeepKeys:
          keep_keys: ['image',
                      'label',
                      'length',
                      'encoder_word_pos',
                      'gsrm_word_pos',
                      'gsrm_slf_attn_bias1',
                      'gsrm_slf_attn_bias2'] 
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1
    num_workers: 4
    use_shared_memory: False
